Repository airtai/nbdev-mkdocs, pull requests merged in 2022-11, with the labels that each got.

#12 Install nbdev along with its dev dependency
  .github/workflows/deploy.yaml
Labels: bug

#19 Write end-to-end walkthrough guide
  .gitignore
  CHANGELOG.md
  Makefile
  mkdocs/docs/images/favicon.ico
  mkdocs/docs/javascripts/extra.js
  mkdocs/docs/javascripts/mathjax.js
  mkdocs/docs/stylesheets/extra.css
  nbdev_mkdocs/_cli.py
  nbdev_mkdocs/mkdocs.py
  nbs/CLI.ipynb
  nbs/Mkdocs.ipynb
  nbs/guides/Guide_00_Installation.ipynb
  nbs/guides/Guide_01_End_To_End_Walkthrough.ipynb
Labels: documentation

#29 Remove unwanted script from Makefile
  Makefile
Labels: bug

#34 Render images added from sub directories in docs
  nbdev_mkdocs/mkdocs.py
  nbs/Mkdocs.ipynb
Labels: bug

#35 Use quarto to convert notebooks into markdown
  .github/workflows/test.yaml
  Makefile
  nbdev_mkdocs/_modidx.py
  nbdev_mkdocs/mkdocs.py
  nbs/Mkdocs.ipynb
  nbs/guides/Guide_00_Installation.ipynb
  nbs/guides/Guide_01_End_To_End_Walkthrough.ipynb
Labels: enhancement
